services:
  odoo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: odoo-cli start
    volumes:
      - ..:/workspace
      - odoo-data:/var/lib/odoo
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - DATABASE=test
      - STAGE=dev
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
  odoo-data:
